"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'app.settings',
    'app.config',
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Bishkek'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' 

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'settings.User'

JAZZMIN_SETTINGS = {
    "site_title": "American Dream",
    "site_header": "American Dream",
    "site_brand": "American Dream",
    "welcome_sign": "Добро пожаловать",
    "copyright": "American Dream",
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_models": [
        "settings.studentpayments",
        "settings.accountingaccount",
        "settings.accountingproject",
        "settings.accountingcategory",
        "settings.task",
        "settings.user",
        "config.crmsetting",
    ],
    "order_with_respect_to": [
        "settings",
        "settings.organization",
        "settings.cursues",
        "settings.groupcourse",
        "settings.individualcourse",
        "settings.calendarevent",
        "settings.student",
        "settings.mentor",
        "settings.tuitionpayment",
        "settings.payment",
        "settings.salary",
        "settings.lead",
        "settings.accountingentry",
        "settings.debtorenrollment",
        "config",
        "config.crmsetting",
    ],
    "custom_links": {
        "settings": [
            {
                "name": "Архив",
                "url": "/admin/archive/",
                "icon": "fas fa-archive",
            },
        ],
        "config": [
            # URL берётся из reverse в CRMAdminSite (см. admin_site.py)
            {"name": "История действий", "icon": "fas fa-history"},
        ],
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "settings.user": "fas fa-user",
        "settings.student": "fas fa-user-graduate",
        "settings.mentor": "fas fa-chalkboard-teacher",
        "settings.cursues": "fas fa-book",
        "settings.organization": "fas fa-building",
        "settings.lead": "fas fa-user-plus",
        "settings.payment": "fas fa-coins",
        "settings.salary": "fas fa-dollar-sign",
        "settings.task": "fas fa-tasks",
        "settings.studentpayments": "fas fa-coins",
        "settings.tuitionpayment": "fas fa-coins",
        "settings.debtorenrollment": "fas fa-exclamation-circle",
        "settings.call": "fas fa-phone",
        "settings.calendarevent": "fas fa-calendar-alt",
        "settings.accountingentry": "fas fa-file-invoice-dollar",
        "settings.accountingaccount": "fas fa-wallet",
        "settings.accountingproject": "fas fa-layer-group",
        "settings.accountingcategory": "fas fa-tags",
        "crm_admin:archive_index": "fas fa-archive",
        "crm_admin:settings_index": "fas fa-cog",
        "config.crmsetting": "fas fa-cog",
        "config.crmbilling": "fas fa-receipt",
        "config.crmabout": "fas fa-info-circle",
    },
    "custom_css": "crm_dashboard/dashboard.css",
    "custom_js": None,
}
