# Generated by Django 4.2 on 2026-04-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursues',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена (с.)'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма к оплате (с.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.cursues', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Оплата за учебу',
                'verbose_name_plural': 'Оплата за учебу',
            },
        ),
        migrations.CreateModel(
            name='DebtorEnrollment',
            fields=[
            ],
            options={
                'verbose_name': 'Должник',
                'verbose_name_plural': 'Должники',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('settings.enrollment',),
        ),
        migrations.CreateModel(
            name='StudentPayments',
            fields=[
            ],
            options={
                'verbose_name': 'Оплата за учебу',
                'verbose_name_plural': 'Оплата за учебу',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('settings.enrollment',),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='uniq_student_course'),
        ),
    ]
