# Generated by Django 4.2 on 2026-04-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_cursues_price_enrollment_debtorenrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFinance',
            fields=[
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('settings.enrollment',),
        ),
    ]
