# Generated by Django 4.2 on 2026-04-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_aboutpage_accountingentry_announcement_appsetting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='StudentFinance',
        ),
    ]
