# Generated by Django 4.2 on 2026-04-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_delete_announcement_delete_inventoryitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCourse',
            fields=[
            ],
            options={
                'verbose_name': 'Групповой курс',
                'verbose_name_plural': 'Групповые',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('settings.cursues',),
        ),
        migrations.CreateModel(
            name='IndividualCourse',
            fields=[
            ],
            options={
                'verbose_name': 'Индивидуальный курс',
                'verbose_name_plural': 'Индивидуальные',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('settings.cursues',),
        ),
        migrations.AddField(
            model_name='cursues',
            name='course_type',
            field=models.CharField(choices=[('group', 'Групповые'), ('individual', 'Индивидуальные')], default='group', max_length=16, verbose_name='Тип курса'),
        ),
    ]
