# Generated by Django 4.2 on 2026-04-28 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_groupcourse_individualcourse_cursues_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursues',
            name='capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='Лимит студентов'),
        ),
        migrations.AddField(
            model_name='cursues',
            name='room',
            field=models.CharField(blank=True, max_length=64, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='cursues',
            name='schedule_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Расписание'),
        ),
        migrations.CreateModel(
            name='CourseDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropped_at', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.cursues', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Покинули курс',
                'verbose_name_plural': 'Покинули курс',
            },
        ),
    ]
