# Generated by Django 4.2 on 2026-04-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_cursues_capacity_cursues_room_cursues_schedule_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursues',
            name='subject',
            field=models.CharField(blank=True, max_length=155, verbose_name='Предмет'),
        ),
    ]
