# Generated by Django 4.2 on 2026-04-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_cursues_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='call',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='call',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='cursues',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='cursues',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='lead',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='task',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
