# Generated by Django 4.2 on 2026-04-28 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_accountingentry_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.cursues', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='online_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на онлайн-конференцию'),
        ),
        migrations.AlterField(
            model_name='cursues',
            name='status',
            field=models.CharField(choices=[('Подготовка курсов', 'Подготовка курсов'), ('Активные курсы', 'Активные курсы'), ('Завершенные курсы', 'Завершенные курсы')], max_length=155, verbose_name='Статус'),
        ),
    ]
