# Generated by Django 4.2 on 2026-04-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_calendarevent_course_calendarevent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('left', 'Ушел'), ('frozen', 'Замороженный')], default='active', max_length=16, verbose_name='Статус'),
        ),
    ]
