# Generated by Django 4.2 on 2026-04-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_student_archived_at_student_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Банковский перевод'), ('card', 'Карта'), ('other', 'Другое')], default='cash', max_length=16, verbose_name='Способ оплаты'),
        ),
    ]
