# Generated by Django 4.2 on 2026-04-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Оплата за учебу',
                'verbose_name_plural': 'Оплата за учебу',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('settings.payment',),
        ),
    ]
