# Generated by Django 4.2 on 2026-04-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_aboutpage_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Ментор', 'Ментор'), ('Менеджер', 'Менеджер'), ('Студент', 'Студент'), ('Администратор', 'Администратор')], default='Администратор', max_length=32, verbose_name='Роль'),
        ),
    ]
