# Generated by Django 4.2 on 2026-05-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods', models.CharField(max_length=255, verbose_name='Периоды')),
                ('amount_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма на момент создания')),
                ('paid_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплачено на момент создания')),
                ('debt_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Долг на момент создания')),
                ('document_text', models.TextField(blank=True, verbose_name='Текст контракта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.cursues', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Контракт курса',
                'verbose_name_plural': 'Контракты курсов',
            },
        ),
        migrations.AddConstraint(
            model_name='coursecontract',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='uniq_course_contract'),
        ),
    ]
