# Generated by Django 4.2 on 2026-05-09 19:05

import app.settings.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_coursecontract_coursecontract_uniq_course_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='contract_file',
            field=models.FileField(blank=True, upload_to='mentor_contracts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), app.settings.models.validate_mentor_contract_pdf], verbose_name='Контракт (PDF)'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ухода'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='departure_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Причина ухода'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='documents_folder',
            field=models.CharField(blank=True, default='', help_text='Ссылка или путь к папке', max_length=500, verbose_name='Папка с документами'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='fixed_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фикс. ставка'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='payment_form',
            field=models.CharField(choices=[('fixed', 'Фиксированная'), ('per_lesson', 'За занятие'), ('hourly', 'Почасовая')], default='fixed', max_length=16, verbose_name='Форма оплаты'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='payment_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для почасовой или за занятие', max_digits=12, null=True, verbose_name='Ставка оплаты'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='workplace',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Место работы'),
        ),
    ]
