# Generated by Django 4.2 on 2026-05-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_mentor_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_voided',
            field=models.BooleanField(default=False, verbose_name='Аннулирован'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Квитанция'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Банковский перевод'), ('card', 'Карта'), ('aiti_transfer', 'Aiti переводы'), ('aiti_cash', 'Aiti наличка'), ('other', 'Другое')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
