# Generated by Django 4.2 on 2026-05-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_payment_description_payment_is_voided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
