# Generated by Django 4.2 on 2026-05-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_add_mentor_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='salary',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries', to='settings.cursues', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='settings.mentor', verbose_name='Ментор'),
        ),
    ]
