# Generated by Django 4.2 on 2026-05-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_salary_comment_salary_course_alter_salary_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='percentage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Например, 30 для 30%%', max_digits=5, null=True, verbose_name='Процент с ученика (%)'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='payment_form',
            field=models.CharField(choices=[('fixed', 'Фиксированная'), ('per_lesson', 'За занятие'), ('hourly', 'Почасовая'), ('percentage', 'Процент с ученика')], default='fixed', max_length=16, verbose_name='Форма оплаты'),
        ),
    ]
