# Generated by Django 4.2 on 2026-05-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_mentor_percentage_rate_alter_mentor_payment_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_pages', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='accountingaccount',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='accountingcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='accountingproject',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='call',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='cursues',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='salary',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='student',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='settings.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='settings.organization', verbose_name='Организация'),
        ),
    ]
