# Generated by Django 4.2 on 2026-05-10 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_organization_aboutpage_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursues',
            name='lessons_per_month',
            field=models.PositiveIntegerField(default=15, verbose_name='Уроков в месяц'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Ментор', 'Ментор'), ('Менеджер', 'Менеджер'), ('Студент', 'Студент'), ('Родитель', 'Родитель'), ('Администратор', 'Администратор')], default='Администратор', max_length=32, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=155, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='settings.organization', verbose_name='Организация')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='settings.student', verbose_name='Студент')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
    ]
