# Generated by Django 4.2 on 2026-05-10 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_cursues_lessons_per_month_alter_user_role_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.AddField(
            model_name='cursues',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Конец курса'),
        ),
        migrations.AddField(
            model_name='parent',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='parents', to='settings.student', verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Ментор', 'Ментор'), ('Менеджер', 'Менеджер'), ('Студент', 'Студент'), ('Администратор', 'Администратор')], default='Администратор', max_length=32, verbose_name='Роль'),
        ),
    ]
