# Generated by Django 4.2 on 2026-05-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_remove_parent_student_cursues_end_parent_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Ментор', 'Ментор'), ('Менеджер', 'Менеджер'), ('Студент', 'Студент'), ('Родитель', 'Родитель'), ('Администратор', 'Администратор')], default='Администратор', max_length=32, verbose_name='Роль'),
        ),
    ]
