# Generated by Django 4.2 on 2026-05-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0026_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='documents_folder',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Папка с документами'),
        ),
        migrations.AddField(
            model_name='student',
            name='from_where',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '—'), ('М', 'Мужской'), ('Ж', 'Женский')], default='', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='student',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер родителя'),
        ),
        migrations.AddField(
            model_name='student',
            name='telegram_nick',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ник в Telegram'),
        ),
    ]
