# Generated by Django 4.2 on 2026-05-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_student_birth_date_student_documents_folder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации')),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('is_additional', models.BooleanField(default=False, verbose_name='Дополнительный урок')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата урока')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='settings.mentor', verbose_name='Ментор')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации')),
                ('title', models.CharField(max_length=255, verbose_name='Название контрольной работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='settings.mentor', verbose_name='Ментор')),
            ],
            options={
                'verbose_name': 'Контрольная работа',
                'verbose_name_plural': 'Контрольные работы',
                'ordering': ['-created_at'],
            },
        ),
    ]
