# Generated by Django 4.2 on 2026-05-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0032_curriculum_module_lesson_curriculum_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='bot_reply',
            field=models.TextField(blank=True, default='', verbose_name='Последний ответ бота'),
        ),
        migrations.AddField(
            model_name='lead',
            name='conversation_log',
            field=models.TextField(blank=True, default='', verbose_name='История переписки'),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Последний вопрос'),
        ),
        migrations.AddField(
            model_name='lead',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Сессия чата'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, default='manual', max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(blank=True, default='Посетитель сайта', max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон'),
        ),
    ]
