# Generated by Codex on 2026-05-31

from django.db import migrations, models


def forwards(apps, schema_editor):
    cursues = apps.get_model("settings", "Cursues")
    for old_status, new_status in {
        "Подготовка курсов": "Подготовка",
        "Активные курсы": "Запущен",
        "Завершенные курсы": "Закончен",
    }.items():
        cursues.objects.filter(status=old_status).update(status=new_status)


def backwards(apps, schema_editor):
    cursues = apps.get_model("settings", "Cursues")
    for new_status, old_status in {
        "Подготовка": "Подготовка курсов",
        "Готов к запуску": "Подготовка курсов",
        "Запущен": "Активные курсы",
        "Приостановлен": "Активные курсы",
        "Закончен": "Завершенные курсы",
        "Архивирован": "Завершенные курсы",
    }.items():
        cursues.objects.filter(status=new_status).update(status=old_status)


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0033_lead_bot_reply_lead_conversation_log_lead_email_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="cursues",
            name="status",
            field=models.CharField(
                choices=[
                    ("Подготовка", "Подготовка"),
                    ("Готов к запуску", "Готов к запуску"),
                    ("Запущен", "Запущен"),
                    ("Приостановлен", "Приостановлен"),
                    ("Закончен", "Закончен"),
                    ("Архивирован", "Архивирован"),
                ],
                max_length=155,
                verbose_name="Статус",
            ),
        ),
    ]
